USE [master]
GO

/****** Object:  Database [BookLibrary]    Script Date: 19/11/2015 03:23:53 a. m. ******/
CREATE DATABASE [BookLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BookLibrary.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BookLibrary_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BookLibrary] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookLibrary] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BookLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookLibrary] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BookLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [BookLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookLibrary] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BookLibrary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookLibrary] SET  READ_WRITE 
GO


